server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

spring:
  application:
    name: loopit.paysheet

  security:
    jwt:
      signature: ${SIGNATURE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
    hikari:
      connection-timeout: ${DB_TIMEOUT}
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    open-in-view: ${DB_OPEN_VIEW}

  aws:
    credentials:
      serviceEndpoint: ${AWS_ENDPOINT}
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucketName: ${AWS_BUCKET_NAME}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

enterprise:
  credential:
    url: ${ENTERPRISE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

