server:
  port: ${SERVER_PORT:8083}

spring:

  application:
    name: contra-cheque

  security:
    auth:
      signature: TESTE

  datasource:
    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3306}/prd?allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:KBf9]xEjq~K}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update

  aws:
    credentials:
      serviceEndpoint: ${AWS_ENDPOINT:http://0.0.0.0:3000}
      accessKey: ${AWS_ACESS_KEY:S3RVER}
      secretKey: ${AWS_SECRET_KEY:S3RVER}
      region: ${AWS_REGION:us-east-1}
      bucketName: ${AWS_BUCKETNAME:funcionarios}

enterprise:
  credential:
    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3306}/principal?allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:KBf9]xEjq~K}


