server:
  port: ${SERVER_PORT:8083}

spring:

  application:
    name: contra-cheque

  security:
    auth:
      signature: TESTE

  datasource:
    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3306}/prd?allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:KBf9]xEjq~K}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update

    #info:
    #project:
    #application: ${spring.application.name}
    #version: @project.version@
    #javaVendor: ${java.runtime.name}
    #javaVersion: ${java.runtime.version}



